### ISSUE TITLE
How to flash the firmware?

### ISSUE THREAD

**Issue by ghost** [urjaman/openwrt-w268r#1]
Hello,

First of all I want to thank you for making this distribution/fork, for Tenda W268R. :)
I have followed the basic instructions in the README file for building the firmware, but sadly I do not know how to flash the "result" to the router.

I have tried with Tenda's tftp on Windows (web.archive.org/web/http://www.tenda.cn/uploadfile/downloads/uploadfile/200911/TENDA%20TFTP.zip), commands from scripts/flash/flash.sh customized for the router and so telnet. I am a beginner regarding openwrt in general.

Regards,
Gustaf Haglund

**Comment by urjaman** [comment]
Firstly, i had some notes etc in a commit at home that I hadnt pushed yet, so please pull those and re-read README.

The device has the same pads for serial as the Tenda W306R V2.0, see http://wiki.openwrt.org/toh/tenda/w306r#serial for a picture and settings. It has a rather simple boot menu that allows loading firmware over tftp to flash or RAM - i usually use the RAM option (i think i press 1) and if it works flash from openwrt.

Also you can backup the old flash memory contents from inside tftp-openwrt-to-RAM so you can go back if needed.

( It was possible to flash a modified tenda firmware (i dont think i can give that) with the tenda web interface to give shell access and that way do whatever you want (including flash the openwrt firmware), but i dont recommend that for anyone... it has 0 backup, with serial you can always try again.. )

**Comment by ghost** [comment]
Pretty complicated with connecting via serial-to-USB, but I will check it out. Thank you. :)
